language: php

sudo: required
dist: trusty
group: edge

cache:
  directories:
    - $HOME/.composer/cache

php:
  - 5.6
  - 7.0
  - hhvm-3.9

matrix:
  fast_finish: true

before_script:
  - composer install --prefer-dist --no-interaction --no-progress

script:
  - vendor/bin/phing ci

after_success:
  - travis_retry php vendor/bin/coveralls -v
