language: php

sudo: required
dist: trusty
group: edge

cache:
  directories:
    - $HOME/.composer/cache

php:
  - 5.6
  - 7.0
  - hhvm-3.9

matrix:
  fast_finish: true
  include:
    - php: hhvm-3.9
      sudo: required
      dist: trusty
      group: edge
    - php: hhvm
      sudo: required
      dist: trusty
      group: edge

before_script:
  - rm -f ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini
  - flags="--prefer-dist"
  - composer install $flags

script:
  - vendor/bin/phing ci
