language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

php:
  - 5.6
  - 7.0
  - hhvm

matrix:
  fast_finish: true

before_script:
    - rm -f ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini
    - flags="--prefer-dist"
    - composer install $flags

script:
    - vendor/bin/phing ci
