build: off
shallow_clone: false
clone_folder: C:\projects\luster
cache:
    - '%APPDATA%\Composer'

environment:
    matrix:
        - php_ver: 7.0.9
        - php_ver: 5.6.17

platform:
  - x86
  - x64

install:
    - choco install -y php -version %php_ver%
    - SET PATH=C:\tools\php;%PATH%
    - cd C:\tools\php
    - copy php.ini-production php.ini
    - echo date.timezone="UTC" >> php.ini
    - echo memory_limit=512M >> php.ini
    - echo extension_dir=ext >> php.ini
    - echo extension=php_curl.dll >> php.ini
    - echo extension=php_openssl.dll >> php.ini
    - cd C:\tools
    - appveyor DownloadFile https://getcomposer.org/composer.phar

before_test:
    - cd C:\projects\luster
    - php C:\tools\composer.phar update --no-interaction

test_script:
    - cd C:\projects\luster
    - vendor\bin\phing
